---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
      storageAccountName: "{{ ansible_env.storageAccountName }}"
      containerName: "{{ ansible_env.containerName }}"
      adlAnalyticsName: "{{ ansible_env.adlAnalyticsName }}"
      adlStoreName: "{{ ansible_env.adlStoreName }}"
      location: "{{ ansible_env.location }}"
      dataFactoryName: "{{ ansible_env.dataFactoryName }}"
      dataFactoryLocation: "{{ ansible_env.dataFactoryLocation }}"
      onPremSqlServerConnectionString: "{{ ansible_env.onPremSqlServerConnectionString }}"
      sqlTableName: "{{ ansible_env.sqlTableName }}"
      outputBlobFolder: "{{ ansible_env.outputBlobFolder }}"
      resourcesgpname: "{{ ansible_env.resourcesgpname }}"
      spkey: "{{ ansible_env.spkey }}"
      servicePrincipalId: "{{ ansible_env.servicePrincipalId }}"
      hostSubscriptionId: "{{ ansible_env.hostSubscriptionId }}"
      tenant: "{{ ansible_env.tenant }}"
      var_SharedKeyVault: 'alankv321'
      templateLink: 'https://raw.githubusercontent.com/alankarmehta/BigDataAutomation/master/Main_Template1.json'
  tasks:
    - name: Deploy ARM template
      
      azure_rm_deployment:
        subscription_id: "{{ hostSubscriptionId }}"
        client_id: "{{ servicePrincipalId }}"
        tenant: "{{ tenant }}"
        secret: "{{ spkey }}"
        resource_group_name: "{{ resourcesgpname }}"
        location: "{{ location }}"
        state: present
        parameters:
          storageAccountName: 
            value: "{{ storageAccountName }}"
          containerName: 
            value: "{{ containerName }}"
          adlAnalyticsName: 
            value: "{{ adlAnalyticsName }}"
          adlStoreName: 
            value: "{{ adlStoreName }}"
          location: 
            value: "{{ location }}"
          dataFactoryName: 
            value: "{{ dataFactoryName }}"
          dataFactoryLocation: 
            value: "{{ dataFactoryLocation }}"
          onPremSqlServerConnectionString: 
            value: "{{ onPremSqlServerConnectionString }}"
          sqlTableName: 
            value: "{{ sqlTableName }}"
          outputBlobFolder: 
            value: "{{ outputBlobFolder }}"
        template_link: '{{ templateLink }}'