---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
      vaults_name: alankv321" 
      vaults_rg_name: demo1234
      secretName: "connstring"
      storageAccountName: "alankarstr01"
      containerName: "alankarctr01"
      adlAnalyticsName: "alankardla01"
      adlStoreName: "alankardls01"
      dataFactoryName: "alankaradf01"
      onPremSqlServerConnectionString: "Server=mysqlvmlabel1.eastus.cloudapp.azure.com,1433;Database=testdb;Integrated Security=false;User ID=Azureadmin;Password=Welcome@12345"
      sqlTableName: "dbo.emp"
      outputBlobFolder: "fromonpremsql"
      resourcesgpname: "alankar01"
      location: "eastus2"
      spkey: "J76B/wvOWWMnLGniHCfAh4AttMVmur8x5J0RRY678SA="
      servicePrincipalId: "3ab325b4-fd99-4a72-b770-12c8c766d4a4"
      hostSubscriptionId: "07494aa9-3134-4cdd-9e14-e0d21257696c"
      tenant: "c160a942-c869-429f-8a96-f8c8296d57db"
      templateLink: 'https://raw.githubusercontent.com/alankarmehta/BigDataAutomation/master/Main_Template1.json'


  tasks:
    - name: AZ Login to Azure
      shell: >
            az login --service-principal
            -u "{{ servicePrincipalId | mandatory }}"
            -p "{{ spkey | mandatory }}"
            --tenant "{{ tenant | mandatory }}" && az account set --subscription "{{ hostSubscriptionId }}"

    - name: Fetch service principal key from shared Key Vault
      shell: >
            az keyvault secret show --name connstring --vault-name alankv321 --query value --output tsv
      register: var_connstring

    - name: Deploy ARM template
      azure_rm_deployment:
        subscription_id: "{{ hostSubscriptionId }}"
        client_id: "{{ servicePrincipalId }}"
        tenant: "{{ tenant }}"
        secret: "{{ spkey }}"
        resource_group_name: "{{ resourcesgpname }}"
        location: "{{ location }}"
        state: present
        parameters:
          vaults_name: 
            value: "{{ vaults_name }}"
          vaults_rg_name: 
            value: "{{ vaults_rg_name }}"
          secretName: 
            value: "{{ secretName }}"
          storageAccountName: 
            value: "{{ storageAccountName }}"
          containerName: 
            value: "{{ containerName }}"
          adlAnalyticsName: 
            value: "{{ adlAnalyticsName }}"
          adlStoreName: 
            value: "{{ adlStoreName }}"
          dataFactoryName: 
            value: "{{ dataFactoryName }}"
          onPremSqlServerConnectionString: 
            value: "{{ var_connstring.stdout }}"
          sqlTableName: 
            value: "{{ sqlTableName }}"
          outputBlobFolder: 
            value: "{{ outputBlobFolder }}"
        template_link: '{{ templateLink }}'